<a href="https://colab.research.google.com/github/daniel-hau-shan12/Python-Colab/blob/main/Numpy_in_Data_science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy In Data Science
- Efficient interface to store and manipulate data
- Core of almost all the data science tools in python
- Numpy used to create and manipulate arrays
- Data is mostly stored in arrays before fed to the ML algo

In [1]:
import numpy as np
np.__version__

'1.23.5'

In [2]:
# Using loops to create lists
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
print(type(L))

<class 'list'>


In [4]:
# Typecast integers list to string list using loops
L2 = []
for c in L:
  L2.append(str(c))
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [5]:
print(type(L2))

<class 'list'>


In [6]:
type(L2[0])

str

In [ ]:
# We cannot use python lists to store data

### Numpy Arrays

In [7]:
# Use np.array() to create numpy array
np.array([1,4,2,5,3])


array([1, 4, 2, 5, 3])

In [9]:
# Upcasting ( converting integers to floats)
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [10]:
# Explicitly set the data type of array
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

2D Arrays
- These are arrays that have rows and columns

In [12]:
np.array([[1,2,3], [4,5,6]], dtype= 'float32') # 2 rows and 3 cols

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

Ways to initialize arrays

In [13]:
# create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
# create a 3x5 floating-point array filled with 1s
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
# creating a 3x3 array of uniformly distributed random values btn 0 and 1
np.random.random((3,3))

array([[0.28560996, 0.59675937, 0.02555368],
       [0.12382552, 0.97853509, 0.23895149],
       [0.22129889, 0.91393289, 0.35773447]])

Basics of Numpy Arrays

In [17]:
x3 = np.random.randint(10, size=(3,4,5))
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


3D Array

In [18]:
np.array([ [[1,2],[3,4]],
          [[5,6], [7,8]] ])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [19]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [20]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [21]:
np.random.random((4,3,2))

array([[[0.95496008, 0.27629447],
        [0.54570097, 0.67368279],
        [0.96390107, 0.96721784]],

       [[0.44592811, 0.79933692],
        [0.50402507, 0.17133529],
        [0.35381783, 0.94265724]],

       [[0.71526838, 0.48579032],
        [0.87258983, 0.50981792],
        [0.36010977, 0.68670367]],

       [[0.15419301, 0.52421826],
        [0.63166534, 0.95053206],
        [0.75327485, 0.7009957 ]]])

Array Indexing
- simple indexing
- negative indexing
- 2D indexing

In [26]:
x1 = np.array([5,6,2,8,9,0,2,])
x1[0]

5

In [24]:
x1[-1]

2

In [25]:
x1[-2]

0

In [27]:
# 2D indexing
x2 = np.array([[3,4,5],
               [3,1,5],
               [5,8,9]])
x2[0,0]

3

In [28]:
x2[2,0]

5

In [29]:
x2[2,-1]

9

Array Slicing

In [31]:
# 1D slicing
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# first five elements
x[:5]

array([0, 1, 2, 3, 4])

In [33]:
# elements after index 5
x[5:]

array([5, 6, 7, 8, 9])

In [34]:
# middle subarray
x[4:7]

array([4, 5, 6])

In [35]:
# every other element
x[::2]

array([0, 2, 4, 6, 8])

In [36]:
# every other element starting at index 1
x[1::2]

array([1, 3, 5, 7, 9])

2D Slicing

In [37]:
y = np.array([[12,5,2,4],
              [7,6,8,8],
              [1,2,4,7]])
y[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [38]:
y[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  4]])

Reshaping arrays

In [39]:
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
#grid = np.arange(1,10).reshape((2,3))
#print(grid)

In [44]:
a= np.array([1,2,3])
b= np.array([4,5,6])
a+b

array([5, 7, 9])